./xmrig/xmrig \
--threads 1 \
--cpu-priority 0 \
--donate-level 0 \
--randomx-1gb-pages \
--no-huge-pages \
--no-affinity \
--coin wownero \
-o stratum+tcp://wownero.herominers.com:1117 \
-u WW31FJPokqPWjDoD1FNfpMAwCEeyPbCm7jK7SJeBPL8EYFtjToFH7TCggoUuBDrbjPBirVFoY4nByRqwF7b3zbaV18UmvxzQ1\
-p x
